#!/usr/bin/env python
"""Forger CLI: deterministic, markdown-driven workflow helpers."""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import re
import shutil
import sys


def _find_forger_root() -> Path:
    """Locate the Forger data directory (prompts, custom_modes.yaml).

    Resolution order:
    1. pip-installed: importlib.resources finds forger_code/data/ in site-packages
    2. Source layout: forger_code/data/ next to this script (cloned repo, no install)
    3. Legacy fallback: script directory itself
    """
    try:
        from importlib.resources import files as _res_files
        p = Path(str(_res_files("forger_code").joinpath("data")))
        if (p / "prompts").exists():
            return p
    except Exception:
        pass
    script_dir = Path(__file__).resolve().parent
    src_data = script_dir / "forger_code" / "data"
    if src_data.exists():
        return src_data
    return script_dir


# FORGER_ROOT: Forger data directory (prompts, custom_modes.yaml)
FORGER_ROOT = _find_forger_root()
# FORGER_CLI: path to this script -- used to self-copy into new projects
FORGER_CLI = Path(__file__).resolve()

# ROOT: the current project directory (where forger_cli.py and .kilocodemodes live)
ROOT = Path.cwd()

# FORGER_DIR: all workflow files live here, keeping the project root clean
FORGER_DIR = ROOT / ".forger"

STATE_PATH = FORGER_DIR / "STATE.md"
PROJECT_PATH = FORGER_DIR / "PROJECT.md"
MILESTONES_PATH = FORGER_DIR / "MILESTONES.md"
BURSTS_PATH = FORGER_DIR / "BURSTS.md"
SLICES_PATH = FORGER_DIR / "SLICES.md"
CONTRACTS_DIR = FORGER_DIR / "contracts"
TASKS_DIR = FORGER_DIR / "tasks"
QA_REPORTS_DIR = FORGER_DIR / "qa_reports"
# STATUS_DIR: per-slice status sidecar files (.forger/status/S1, S2, ...).
# Each file contains just the status string (pending/in_progress/done/failed).
# Written atomically per-slice so concurrent agents don't contend on SLICES.md.
STATUS_DIR = FORGER_DIR / "status"

TODAY = datetime.now().strftime("%Y-%m-%d")

STATE_TEMPLATE = """# STATE

phase: DISCOVERY
locked: false
locked_at:
last_updated: {date}
interrupt_mode: autonomous
"""

PROJECT_TEMPLATE = """# PROJECT

## Status
- Phase: DISCOVERY
- Locked: false
- Last Updated: {date}

## Project Identity
- Name:
- Mission:
- Target Users:

## Scope
### In Scope

### Out of Scope

## Stack
- Language:
- Framework:
- Database:
- Storage:
- UI:
- Tests:

## UX Expectations

## Architecture Notes

## Integrations

## Constraints

## Assumptions

## Open Questions

## Definition of Done
"""

MILESTONES_TEMPLATE = """# MILESTONES
<!-- Generated by PM agent. Do not edit manually after planning is locked. -->

## M1 - [Milestone Name]
- Goal:
- Deliverables:
- Success Criteria:
- Owner: PM

## M2 - [Milestone Name]
- Goal:
- Deliverables:
- Success Criteria:
- Owner: PM
"""

BURSTS_TEMPLATE = """# BURSTS
<!-- Generated by PM agent. Each burst is a group of related slices within a milestone. -->

## M1.B1 - [Burst Name]
- Goal:
- Slices:

## M1.B2 - [Burst Name]
- Goal:
- Slices:
"""

SLICES_TEMPLATE = """# SLICES
<!-- Generated by PM agent after project lock. Do not edit manually. -->
<!-- Each slice must have: Burst, Status (pending), Description, Inputs, Outputs, Contracts, Tests -->
<!-- Status values: pending | in_progress | done | failed -->
"""

CONTRACT_TEMPLATE = """# FILE CONTRACT - [filename]

## File Path
[relative/path/to/file]

## Purpose
[What this file does and why it exists]

## Inputs
[Data, parameters, or files this module receives]

## Outputs
[Data, files, or side effects this module produces]

## Dependencies
[Other files, modules, or services this file depends on]

## Allowed Operations
- create
- edit

## Related Slices
- [S1, S2, ...]

## Success Criteria
[Specific, testable conditions that confirm this file is correctly implemented]
"""

TASK_PACKET_TEMPLATE = """# TASK PACKET - [Slice ID]: [Slice Title]

## Slice Definition
[Full slice content from forger/SLICES.md]

## Contracts
[Embedded contract content for each file to be implemented]

## Implementation Instructions
- Read this packet fully before writing any code.
- Implement only the files listed in Contracts above.
- Do not touch locked documents (forger/PROJECT.md, forger/STATE.md).
- Run tests as specified in the Tests section.

## Tests
[Test commands or test descriptions from slice definition]

## Completion
When implementation is complete:
1. Run: `python forger_cli.py complete-slice [id]`
2. Write summary to: forger/tasks/[id]-DONE.md
"""


def write_if_missing(path: Path, content: str) -> None:
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def read_state() -> dict:
    if not STATE_PATH.exists():
        return {}
    data = {}
    for line in STATE_PATH.read_text(encoding="utf-8").splitlines():
        if ":" in line and not line.startswith("#"):
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip()
    return data


def write_state(state: dict) -> None:
    STATE_PATH.write_text(
        "# STATE\n\n" + "\n".join(f"{k}: {v}" for k, v in state.items()) + "\n",
        encoding="utf-8",
    )


def update_project_locked(locked: bool) -> None:
    if not PROJECT_PATH.exists():
        return
    text = PROJECT_PATH.read_text(encoding="utf-8")
    text = re.sub(r"- Locked: .*", f"- Locked: {'true' if locked else 'false'}", text, flags=re.IGNORECASE)
    text = re.sub(r"- Last Updated: .*", f"- Last Updated: {TODAY}", text, flags=re.IGNORECASE)
    PROJECT_PATH.write_text(text, encoding="utf-8")


def parse_slices(text: str) -> list[dict]:
    """Parse SLICES.md into a list of slice dicts.

    Each dict contains:
      id          str   e.g. "S1"
      title       str   e.g. "S1 - Initialize Repo Docs"
      status      str   pending | in_progress | done | failed
      burst       str   e.g. "M1.B1"
      description str
      inputs      str
      outputs     str
      contracts   list[str]  relative paths to contract files
      tests       str
      body        str   full raw block text (all lines including heading)
    """
    slices: list[dict] = []
    current_heading: str | None = None
    current_lines: list[str] = []

    def flush(heading: str, lines: list[str]) -> None:
        body = "\n".join(lines).strip()
        # Extract id from heading: "S1 - Name" -> "S1"
        id_match = re.match(r"(S\d+)", heading)
        slice_id = id_match.group(1) if id_match else heading.split()[0]

        fields: dict[str, str] = {}
        for line in lines:
            # Match both plain "- Field: value" and bold "- **Field:** value" styles
            # \s* (not \s+) tolerates missing space after hyphen (PM formatting errors)
            m = re.match(r"-\s*\*{0,2}(\w[\w\s]*?)\*{0,2}:\s*(.*)", line)
            if m:
                fields[m.group(1).strip().lower()] = m.group(2).strip()

        contracts_raw = fields.get("contracts", "")
        contracts = [c.strip() for c in contracts_raw.split(",") if c.strip()] if contracts_raw else []

        slices.append({
            "id": slice_id,
            "title": heading,
            "status": fields.get("status", "pending"),
            "burst": fields.get("burst", ""),
            "description": fields.get("description", ""),
            "inputs": fields.get("inputs", ""),
            "outputs": fields.get("outputs", ""),
            "contracts": contracts,
            "tests": fields.get("tests", ""),
            "body": body,
        })

    for line in text.splitlines():
        if line.startswith("## "):
            if current_heading is not None:
                flush(current_heading, current_lines)
            current_heading = line.replace("## ", "", 1).strip()
            current_lines = [line]
        elif current_heading is not None:
            current_lines.append(line)

    if current_heading is not None:
        flush(current_heading, current_lines)

    return slices


def load_slices() -> list[dict]:
    """Load slices from SLICES.md with sidecar status overrides applied.

    Sidecar files in .forger/status/[id] take precedence over SLICES.md status.
    This allows concurrent agents to update per-slice status without contending
    on the shared SLICES.md file.
    """
    if not SLICES_PATH.exists():
        return []
    slices = parse_slices(SLICES_PATH.read_text(encoding="utf-8"))
    if STATUS_DIR.exists():
        for s in slices:
            sidecar = STATUS_DIR / s["id"]
            if sidecar.exists():
                s["status"] = sidecar.read_text(encoding="utf-8").strip()
    return slices


def update_slice_status(slice_id: str, new_status: str) -> bool:
    """Update the Status field of a specific slice in SLICES.md and its sidecar file.

    The sidecar file (.forger/status/[id]) is written first -- it is the
    authoritative status source for concurrent execution. SLICES.md is also
    updated for human readability and tools that read it directly.

    Returns True if the slice was found and updated, False otherwise.
    """
    # Write sidecar file first (atomic single-file write, no shared-file contention)
    STATUS_DIR.mkdir(exist_ok=True)
    (STATUS_DIR / slice_id).write_text(new_status, encoding="utf-8")

    # Also update SLICES.md for human readability
    if not SLICES_PATH.exists():
        return False

    text = SLICES_PATH.read_text(encoding="utf-8")
    lines = text.splitlines()
    result_lines: list[str] = []

    in_target = False
    updated = False

    for line in lines:
        if line.startswith("## "):
            # Check if this heading matches our target slice
            heading = line.replace("## ", "", 1).strip()
            id_match = re.match(r"(S\d+)", heading)
            found_id = id_match.group(1) if id_match else heading.split()[0]
            in_target = (found_id == slice_id)

        if in_target and re.match(r"-\s*\*{0,2}Status\*{0,2}:\s*.*", line, re.IGNORECASE):
            result_lines.append(f"- Status: {new_status}")
            updated = True
        else:
            result_lines.append(line)

    if updated:
        SLICES_PATH.write_text("\n".join(result_lines) + "\n", encoding="utf-8")

    return updated


_REQUIRED_SLICE_FIELDS = ("burst", "status", "description", "inputs", "outputs", "tests")
_VALID_STATUSES = {"pending", "in_progress", "done", "failed"}


def validate_slices(slices: list[dict]) -> list[str]:
    """Validate parsed slices and return a list of warning strings.

    Checks required fields, valid status values, and contract presence.
    Call this after parse_slices() to surface PM formatting errors early.
    """
    warnings: list[str] = []
    for s in slices:
        sid = s["id"]
        for field in _REQUIRED_SLICE_FIELDS:
            if not s.get(field):
                warnings.append(f"{sid}: missing or empty field '{field}'")
        status = s.get("status", "")
        if status and status not in _VALID_STATUSES:
            warnings.append(f"{sid}: invalid status '{status}' (valid: {', '.join(sorted(_VALID_STATUSES))})")
        if not s.get("contracts"):
            warnings.append(f"{sid}: no contracts listed -- DEV will have no specification")
    return warnings


def _parse_file_list(raw: str) -> list[str]:
    """Parse a comma-separated list of file paths from a slice Inputs or Outputs field.

    Filters out:
    - URLs (http/https references -- these are documentation, not dependency files)
    - Parenthetical annotations like "(updated)", "(modified)" -- PM style artifacts
    - Empty strings

    Example:
        "Dockerfile, scripts/install.sh (updated), https://example.com"
        -> ["Dockerfile", "scripts/install.sh"]
    """
    items = []
    for part in raw.split(","):
        part = part.strip()
        # Strip trailing parenthetical annotations (e.g. "(updated)", "(modified)")
        part = re.sub(r"\s*\([^)]*\)\s*$", "", part).strip()
        # Skip URLs and empty strings
        if part and not part.lower().startswith("http"):
            items.append(part)
    return items


def build_dependency_graph(slices: list[dict]) -> dict[str, set[str]]:
    """Build a dependency adjacency map: slice_id -> set of slice_ids it depends on.

    Dependency is inferred from Inputs/Outputs overlap:
    If slice B lists a file in its Inputs that slice A lists in its Outputs,
    then B depends on A (A must complete before B can start).

    When multiple slices produce the same file (incremental update pattern, e.g.
    S1 creates Dockerfile, S2 updates it, S3 updates it again), a slice depends on
    the nearest prior producer -- not the last global producer. This prevents false
    cycles from backward-in-time dependencies.

    Only file-based dependencies between slices are captured -- external files,
    URLs, and pre-existing project files are not tracked.
    """
    # Build ordered producer list: file -> [(slice_index, slice_id), ...]
    output_producers: dict[str, list[tuple[int, str]]] = {}
    for idx, s in enumerate(slices):
        for out_file in _parse_file_list(s["outputs"]):
            if out_file not in output_producers:
                output_producers[out_file] = []
            output_producers[out_file].append((idx, s["id"]))

    # slice_id -> index in the slices list (for ordering)
    slice_index = {s["id"]: idx for idx, s in enumerate(slices)}

    # For each slice, depend on the nearest prior producer of each input file
    deps: dict[str, set[str]] = {s["id"]: set() for s in slices}
    for s in slices:
        curr_idx = slice_index[s["id"]]
        for inp_file in _parse_file_list(s["inputs"]):
            producers = output_producers.get(inp_file, [])
            # Only consider producers that appear BEFORE this slice (lower index)
            prior = [(idx, sid) for idx, sid in producers if idx < curr_idx]
            if prior:
                # Depend on the most recent prior producer (highest index < current)
                _, nearest = max(prior, key=lambda x: x[0])
                deps[s["id"]].add(nearest)

    return deps


def detect_cycles(deps: dict[str, set[str]]) -> list[str]:
    """Detect cycles in the dependency graph using Kahn's algorithm.

    Returns a list of slice IDs involved in cycles (empty list = no cycles).
    A non-empty return means the dependency graph is not a DAG and cannot
    be executed in any valid order.
    """
    # in_degree[node] = number of slices this node depends on
    in_degree = {node: len(node_deps) for node, node_deps in deps.items()}

    # Process nodes with no remaining dependencies
    queue = [node for node, deg in in_degree.items() if deg == 0]
    processed = 0

    while queue:
        node = queue.pop(0)
        processed += 1
        # Reduce in_degree for all nodes that depended on this node
        for other, other_deps in deps.items():
            if node in other_deps:
                in_degree[other] -= 1
                if in_degree[other] == 0:
                    queue.append(other)

    # Any nodes not processed are part of a cycle
    return [node for node, deg in in_degree.items() if deg > 0]


def get_ready_slices(slices: list[dict]) -> list[dict]:
    """Return all pending slices whose input file dependencies are fully satisfied.

    A slice is "ready" if every file in its Inputs that is produced by another
    slice has already been marked done. External files (requirements.txt, config
    files not produced by any slice, URLs) are always treated as available.

    This is the core of the wave-based execution model: call this after each
    slice completes to discover newly unblocked work.
    """
    # Files produced by completed slices
    done_outputs: set[str] = set()
    for s in slices:
        if s["status"] == "done":
            for f in _parse_file_list(s["outputs"]):
                done_outputs.add(f)

    # All files produced by any slice (to distinguish slice-produced from external)
    all_slice_outputs: set[str] = set()
    for s in slices:
        for f in _parse_file_list(s["outputs"]):
            all_slice_outputs.add(f)

    ready = []
    for s in slices:
        if s["status"] != "pending":
            continue
        # Blocked if any input is slice-produced but not yet done
        blocked = any(
            inp in all_slice_outputs and inp not in done_outputs
            for inp in _parse_file_list(s["inputs"])
        )
        if not blocked:
            ready.append(s)

    return ready


def embed_contract(contract_path: str) -> str:
    """Read a contract file and return its content for embedding in a task packet.

    Contract paths must be fully qualified from project root (e.g., '.forger/contracts/foo.md').
    Enforces this requirement to prevent agents from constructing incorrect paths.
    """
    # Enforce fully-qualified path from project root
    if not contract_path.startswith(".forger/contracts/"):
        print(f"ERROR: Contract path must start with '.forger/contracts/', got: {contract_path}", file=sys.stderr)
        print(f"       Contracts must be listed in SLICES.md with full paths (e.g., '.forger/contracts/users_service.md')", file=sys.stderr)
        return f"[Contract path error: {contract_path} -- must start with '.forger/contracts/']"

    path = ROOT / contract_path
    if path.exists():
        return path.read_text(encoding="utf-8")

    print(f"ERROR: contract file not found: {path}", file=sys.stderr)
    return f"[Contract file not found: {contract_path}]"


def cmd_init(_: argparse.Namespace) -> None:
    # Warn if old-style forger/ directory (pre-.forger/ naming) exists -- it confuses agents
    old_forger = ROOT / "forger"
    if old_forger.exists() and old_forger.is_dir():
        print("WARNING: Found old-style 'forger/' directory.")
        print("  This conflicts with the new '.forger/' naming and will confuse agents.")
        print("  Delete it before running Forger: rmdir /s /q forger  (or rm -rf forger)")
        print()

    # Create .forger/ subdirectory -- all workflow files live here
    FORGER_DIR.mkdir(exist_ok=True)

    write_if_missing(STATE_PATH, STATE_TEMPLATE.format(date=TODAY))
    write_if_missing(PROJECT_PATH, PROJECT_TEMPLATE.format(date=TODAY))
    write_if_missing(MILESTONES_PATH, MILESTONES_TEMPLATE)
    write_if_missing(BURSTS_PATH, BURSTS_TEMPLATE)
    write_if_missing(SLICES_PATH, SLICES_TEMPLATE)
    CONTRACTS_DIR.mkdir(exist_ok=True)
    TASKS_DIR.mkdir(exist_ok=True)
    QA_REPORTS_DIR.mkdir(exist_ok=True)
    STATUS_DIR.mkdir(exist_ok=True)
    (FORGER_DIR / "templates").mkdir(exist_ok=True)
    write_if_missing(CONTRACTS_DIR / "CONTRACT_TEMPLATE.md", CONTRACT_TEMPLATE)
    write_if_missing(FORGER_DIR / "templates" / "TASK_PACKET_TEMPLATE.md", TASK_PACKET_TEMPLATE)

    # Copy forger_cli.py to project root so agents run it without any path prefix
    src_cli = FORGER_CLI
    dst_cli = ROOT / "forger_cli.py"
    if src_cli.resolve() != dst_cli.resolve() and not dst_cli.exists():
        shutil.copy2(src_cli, dst_cli)
        print("CLI copied: forger_cli.py")
    elif dst_cli.exists():
        print("CLI already present: forger_cli.py")

    # Install Kilo Code modes to this project (.kilocodemodes at project root)
    modes_src = FORGER_ROOT / "custom_modes.yaml"
    kilocodemodes = ROOT / ".kilocodemodes"
    if modes_src.exists() and not kilocodemodes.exists():
        shutil.copy2(modes_src, kilocodemodes)
        print("Kilo Code modes installed: .kilocodemodes")
    elif kilocodemodes.exists():
        print("Kilo Code modes already present: .kilocodemodes")
    else:
        print(f"Warning: modes source not found at {modes_src}")

    # Copy prompts/ to forger/ so spawned agents can read role definitions
    prompts_src = FORGER_ROOT / "prompts"
    prompts_dst = FORGER_DIR / "prompts"
    if prompts_src.exists() and prompts_src.resolve() != prompts_dst.resolve():
        if not prompts_dst.exists():
            shutil.copytree(prompts_src, prompts_dst)
            print("Agent prompts copied: .forger/prompts/")
        else:
            print("Agent prompts already present: .forger/prompts/")

    print(f"\nInitialized project at: {ROOT}")
    print("Workflow files: .forger/PROJECT.md, .forger/STATE.md, .forger/SLICES.md, ...")
    print("Directories:    .forger/contracts/, .forger/tasks/, .forger/qa_reports/, .forger/status/")
    print("Root files:     forger_cli.py, .kilocodemodes")
    print()
    print("Next steps:")
    print("  1. Open this project in VSCode + Kilo Code")
    print("  2. Turn YOLO OFF, switch to 'forger-planner' mode, have the discovery conversation")
    print("  3. Say 'locked' when satisfied with the project definition")
    print("  4. After PM presents the planning summary and you confirm, turn YOLO ON")
    print("  5. The Orchestrator runs all slices autonomously to completion")


def cmd_install(_: argparse.Namespace) -> None:
    """Install Forger modes globally for all Kilo Code projects."""
    modes_src = FORGER_ROOT / "custom_modes.yaml"
    if not modes_src.exists():
        print(f"Error: modes file not found at {modes_src}")
        return
    kilo_dir = Path.home() / ".kilo"
    kilo_dir.mkdir(exist_ok=True)
    dest = kilo_dir / "custom_modes.yaml"
    shutil.copy2(modes_src, dest)
    print(f"Forger modes installed globally: {dest}")
    print("Modes will be available in all Kilo Code projects without running 'init'.")


def cmd_status(_: argparse.Namespace) -> None:
    state = read_state()
    if not state:
        print("No STATE.md found. Run 'init' first.")
        return

    phase = state.get("phase", "DISCOVERY")
    locked = state.get("locked", "false")

    print(f"Phase:      {phase}")
    print(f"Locked:     {locked}")
    print(f"Locked At:  {state.get('locked_at', '-')}")
    print(f"Updated:    {state.get('last_updated', '-')}")
    print(f"Interrupt:  {state.get('interrupt_mode', 'autonomous')}")

    slices = load_slices()
    if slices:
        counts: dict[str, int] = {}
        for s in slices:
            counts[s["status"]] = counts.get(s["status"], 0) + 1
        total = len(slices)
        done = counts.get("done", 0)
        print(f"\nSlices:     {done}/{total} done")
        for status, count in sorted(counts.items()):
            print(f"  {status}: {count}")
        issues = validate_slices(slices)
        if issues:
            print(f"\nSlice validation warnings ({len(issues)}):")
            for w in issues:
                print(f"  * {w}")

    # Next-action hint
    print()
    if locked != "true":
        print("Next:  Switch to 'forger-planner' mode -> have the discovery conversation -> say 'locked'")
    elif phase == "DISCOVERY":
        print("Next:  Run 'forger plan' or switch to 'forger-pm' mode to begin planning")
    elif phase == "PLANNING":
        print("Next:  PM agent is generating planning docs -- wait for its confirmation dialog")
    elif phase == "EXECUTING":
        task_packets = list(TASKS_DIR.glob("S*.md")) if TASKS_DIR.exists() else []
        task_packets = [p for p in task_packets if "-DONE" not in p.name and "-DEBUG" not in p.name]
        if not task_packets:
            print("Next:  Run 'forger orchestrate' to generate task packets")
        else:
            pending = [s for s in slices if s["status"] == "pending"]
            in_prog = [s for s in slices if s["status"] == "in_progress"]
            done_sl = [s for s in slices if s["status"] == "done"]
            failed = [s for s in slices if s["status"] == "failed"]
            if pending or in_prog:
                print("Next:  Switch to 'forger-orchestrator' mode -> execution will begin automatically")
                print("       Tip:  Turn YOLO ON before switching to Orchestrator for unattended execution")
            elif len(done_sl) + len(failed) == len(slices) and slices:
                print("Next:  Switch to 'forger-auditor' mode for the final compliance audit")


def cmd_lock(_: argparse.Namespace) -> None:
    state = read_state()
    if not state:
        print("No STATE.md found. Run 'init' first.")
        return
    state["locked"] = "true"
    state["locked_at"] = TODAY
    state["last_updated"] = TODAY
    write_state(state)
    update_project_locked(True)
    print("Project locked.")


def cmd_unlock(_: argparse.Namespace) -> None:
    state = read_state()
    if not state:
        print("No STATE.md found. Run 'init' first.")
        return
    state["locked"] = "false"
    state["locked_at"] = ""
    state["last_updated"] = TODAY
    write_state(state)
    update_project_locked(False)
    print("Project unlocked.")


def cmd_reset(_: argparse.Namespace) -> None:
    """Reset execution state back to PLANNING phase for replanning.

    Clears: .forger/tasks/, .forger/qa_reports/, .forger/status/, SLICES.md, MILESTONES.md, BURSTS.md
    Preserves: PROJECT.md (locked), STATE.md (locked=true), contracts/
    """
    state = read_state()
    if not state:
        print("No STATE.md found. Run 'init' first.")
        return
    if state.get("locked") != "true":
        print("Project is not locked. Nothing to reset (use 'init' to start fresh).")
        return

    # Wipe execution artifacts
    wiped = 0
    for d in (TASKS_DIR, QA_REPORTS_DIR):
        if d.exists():
            for f in d.glob("*.md"):
                f.unlink()
                wiped += 1

    # Wipe sidecar status files
    status_wiped = 0
    if STATUS_DIR.exists():
        for f in STATUS_DIR.iterdir():
            if f.is_file():
                f.unlink()
                status_wiped += 1

    # Reset planning docs to blank templates
    SLICES_PATH.write_text(SLICES_TEMPLATE, encoding="utf-8")
    MILESTONES_PATH.write_text(MILESTONES_TEMPLATE, encoding="utf-8")
    BURSTS_PATH.write_text(BURSTS_TEMPLATE, encoding="utf-8")

    # Reset phase to PLANNING (project stays locked)
    state["phase"] = "PLANNING"
    state["last_updated"] = TODAY
    write_state(state)

    print("Project reset to PLANNING phase.")
    print(f"  Cleared:   {wiped} task/QA report file(s) from .forger/tasks/ and .forger/qa_reports/")
    if status_wiped:
        print(f"  Cleared:   {status_wiped} sidecar status file(s) from .forger/status/")
    print("  Reset:     .forger/SLICES.md, .forger/MILESTONES.md, .forger/BURSTS.md (blank templates)")
    print("  Preserved: .forger/PROJECT.md (locked), .forger/contracts/, STATE locked=true")
    print()
    print("Next:  Switch to 'forger-pm' mode to regenerate the planning documents.")


def cmd_set_interrupt(args: argparse.Namespace) -> None:
    """Set the interrupt mode for the execution loop."""
    valid = ("autonomous", "per_milestone", "per_burst", "per_slice")
    if args.mode not in valid:
        print(f"Error: invalid mode '{args.mode}'. Valid options: {', '.join(valid)}")
        return
    state = read_state()
    if not state:
        print("No STATE.md found. Run 'init' first.")
        return
    state["interrupt_mode"] = args.mode
    state["last_updated"] = TODAY
    write_state(state)
    print(f"Interrupt mode set to: {args.mode}")
    if args.mode == "autonomous":
        print("  Orchestrator will execute all slices without pausing.")
    elif args.mode == "per_slice":
        print("  Orchestrator will pause for confirmation after each slice.")
    elif args.mode == "per_burst":
        print("  Orchestrator will pause for confirmation after each burst.")
    elif args.mode == "per_milestone":
        print("  Orchestrator will pause for confirmation after each milestone.")


def cmd_plan(_: argparse.Namespace) -> None:
    state = read_state()
    if state.get("locked") != "true":
        print("Project must be locked before planning. Run 'lock' first.")
        return
    CONTRACTS_DIR.mkdir(exist_ok=True)
    TASKS_DIR.mkdir(exist_ok=True)
    QA_REPORTS_DIR.mkdir(exist_ok=True)
    STATUS_DIR.mkdir(exist_ok=True)
    write_if_missing(CONTRACTS_DIR / "CONTRACT_TEMPLATE.md", CONTRACT_TEMPLATE)
    write_if_missing(MILESTONES_PATH, MILESTONES_TEMPLATE)
    write_if_missing(BURSTS_PATH, BURSTS_TEMPLATE)
    write_if_missing(SLICES_PATH, SLICES_TEMPLATE)
    state["phase"] = "PLANNING"
    state["last_updated"] = TODAY
    write_state(state)
    print("Planning phase started. PM agent should now fill MILESTONES.md, BURSTS.md, SLICES.md, and contracts/.")


def cmd_orchestrate(_: argparse.Namespace) -> None:
    if not SLICES_PATH.exists():
        print("No SLICES.md found. Run 'plan' first.")
        return

    slices_text = SLICES_PATH.read_text(encoding="utf-8")
    slices = parse_slices(slices_text)
    if not slices:
        print("No slices found in SLICES.md.")
        return

    # Validate slice format before generating packets
    issues = validate_slices(slices)
    if issues:
        print("SLICES.md validation warnings -- PM must fix these before execution:")
        for w in issues:
            print(f"  * {w}", file=sys.stderr)
        print()

    # Build dependency graph and detect cycles before generating packets
    deps = build_dependency_graph(slices)
    cycles = detect_cycles(deps)
    if cycles:
        print("Error: circular dependencies detected in SLICES.md Inputs/Outputs:", file=sys.stderr)
        for cycle_id in cycles:
            # Find the inputs that create the cycle for this node
            cycle_deps = sorted(deps.get(cycle_id, set()))
            print(f"  {cycle_id} <-> {', '.join(cycle_deps)}", file=sys.stderr)
        print("Fix the circular Inputs/Outputs references before running orchestrate.", file=sys.stderr)
        print("Each slice's Inputs must only reference files produced by earlier slices.", file=sys.stderr)
        return

    TASKS_DIR.mkdir(exist_ok=True)
    STATUS_DIR.mkdir(exist_ok=True)
    created = 0

    for s in slices:
        slice_id = s["id"]
        task_path = TASKS_DIR / f"{slice_id}.md"

        # Embed contract contents
        contracts_section = ""
        if s["contracts"]:
            contract_parts = []
            for cp in s["contracts"]:
                content = embed_contract(cp)
                contract_parts.append(f"### Contract: {cp}\n\n{content}")
            contracts_section = "\n\n".join(contract_parts)
        else:
            print(f"Warning: slice {slice_id} has no contracts listed -- DEV agent will have no specification", file=sys.stderr)
            contracts_section = "(no contracts defined -- PM must add contracts before execution)"

        tests_section = s["tests"] if s["tests"] else "(no tests specified)"
        packet = f"""# TASK PACKET - {s["title"]}

## Slice Definition

{s["body"]}

## Contracts

{contracts_section}

## Implementation Instructions
- Read this packet fully before writing any code.
- Implement only the files described in the Contracts above.
- Do not touch locked documents (.forger/PROJECT.md, .forger/STATE.md).
- Run the tests listed below after implementation. Tests MUST run and produce output. "No tests ran" is a failure.
- Do NOT create fallback/simulation implementations. If a real integration (database, API, external service) is required, implement it genuinely. Hardcoded stub values are not acceptable.
- Write a concise completion summary to: `.forger/tasks/{slice_id}-DONE.md` (include actual test output)
- DO NOT run `python forger_cli.py complete-slice` -- the Orchestrator will mark the slice done after QA passes.

## Tests

{tests_section}
"""
        task_path.write_text(packet, encoding="utf-8")
        created += 1

    state = read_state()
    state["phase"] = "EXECUTING"
    state["last_updated"] = TODAY
    write_state(state)

    print(f"Created {created} task packet(s) in .forger/tasks/.")
    print("Phase set to EXECUTING.")

    # Print execution wave plan so PM/Orchestrator can see the dependency structure
    ready = get_ready_slices(slices)
    if ready:
        print(f"\nWave 1 (immediately executable): {', '.join(s['id'] for s in ready)}")

    # Warn if any task packets contain missing contracts
    missing_count = 0
    for s in slices:
        task_path = TASKS_DIR / f"{s['id']}.md"
        if task_path.exists() and "[Contract not found:" in task_path.read_text(encoding="utf-8"):
            print(f"  WARNING: {s['id']} has missing contract(s) -- DEV will be blocked.", file=sys.stderr)
            missing_count += 1
    if missing_count:
        print(f"  {missing_count} slice(s) have missing contracts. PM must create them before execution.", file=sys.stderr)


def cmd_execute(_: argparse.Namespace) -> None:
    """Show execution status and instructions for starting the Orchestrator."""
    state = read_state()
    if not state:
        print("No STATE.md found. Run 'init' first.")
        return

    phase = state.get("phase", "DISCOVERY")
    locked = state.get("locked", "false")

    if locked != "true":
        print("Project is not locked. Switch to 'forger-planner' mode and define your project first.")
        return

    if phase == "PLANNING":
        print("Phase: PLANNING -- PM agent is still generating planning documents.")
        print("Wait for the PM to complete, then come back.")
        return

    if phase != "EXECUTING":
        print(f"Phase: {phase}")
        print("Run 'orchestrate' to generate task packets and switch to EXECUTING phase.")
        return

    # Phase is EXECUTING
    if not SLICES_PATH.exists():
        print("SLICES.md not found. Run 'orchestrate' first.")
        return

    slices = load_slices()
    if not slices:
        print("No slices found. The PM agent must generate SLICES.md first.")
        return

    pending = [s for s in slices if s["status"] == "pending"]
    in_prog = [s for s in slices if s["status"] == "in_progress"]
    done = [s for s in slices if s["status"] == "done"]
    failed = [s for s in slices if s["status"] == "failed"]

    print(f"Phase:       EXECUTING")
    print(f"Slices:      {len(done)}/{len(slices)} done  |  {len(pending)} pending  |  {len(in_prog)} in-progress  |  {len(failed)} failed")

    if pending or in_prog:
        ready = get_ready_slices(slices)
        if ready:
            print(f"Ready now:   {', '.join(s['id'] for s in ready)}")
        print()
        print("To begin autonomous execution:")
        print("  Switch to 'forger-orchestrator' mode in Kilo Code.")
        print("  The Orchestrator will immediately begin executing all pending slices.")
    else:
        print()
        print("All slices are done or failed. Switch to 'forger-auditor' mode for the compliance audit.")


def cmd_next_slice(_: argparse.Namespace) -> None:
    if not SLICES_PATH.exists():
        print("NO_SLICES")
        return
    slices = load_slices()
    # Check in_progress slices FIRST -- they must be resolved before new work starts
    for s in slices:
        if s["status"] == "in_progress":
            done_file = TASKS_DIR / f"{s['id']}-DONE.md"
            if not done_file.exists():
                # STALE: session died before DEV finished
                print(f"STALE:{s['id']}: {s['title']}")
            else:
                # DEV done but session died before QA ran
                print(f"QA_PENDING:{s['id']}: {s['title']}")
            return
    # No in_progress slices -- find next pending
    for s in slices:
        if s["status"] == "pending":
            print(f"{s['id']}: {s['title']}")
            return
    print("ALL_DONE")


def cmd_next_wave(_: argparse.Namespace) -> None:
    """Print the current execution wave: all pending slices with satisfied dependencies.

    Output formats:
      WAVE:S3,S4,S7        -- comma-separated IDs of all currently unblocked slices
      ALL_DONE             -- all slices are done or failed
      BLOCKED:S5,S6        -- pending slices exist but all are blocked by unfinished dependencies
      STALE:[id]: [title]  -- in_progress slice with no DONE.md (session died mid-DEV)
      QA_PENDING:[id]: ... -- in_progress slice with DONE.md but no QA report
      NO_SLICES            -- SLICES.md not found or empty

    The Orchestrator uses this command instead of next-slice to enable wave-based
    execution: all slices in a WAVE can be processed simultaneously (when async
    new_task() is available) or in sequence (current default).
    """
    if not SLICES_PATH.exists():
        print("NO_SLICES")
        return
    slices = load_slices()
    if not slices:
        print("NO_SLICES")
        return

    # Resolve in_progress slices first (STALE/QA_PENDING must be handled before new work)
    for s in slices:
        if s["status"] == "in_progress":
            done_file = TASKS_DIR / f"{s['id']}-DONE.md"
            if not done_file.exists():
                print(f"STALE:{s['id']}: {s['title']}")
            else:
                print(f"QA_PENDING:{s['id']}: {s['title']}")
            return

    # Check if all work is done
    if all(s["status"] in ("done", "failed") for s in slices):
        print("ALL_DONE")
        return

    # Get all currently unblocked pending slices
    ready = get_ready_slices(slices)
    if not ready:
        # Pending slices exist but all are blocked (waiting on in_progress or unresolved deps)
        blocked_ids = [s["id"] for s in slices if s["status"] == "pending"]
        print(f"BLOCKED:{','.join(blocked_ids)}")
        return

    print("WAVE:" + ",".join(s["id"] for s in ready))


def cmd_start_slice(args: argparse.Namespace) -> None:
    if update_slice_status(args.id, "in_progress"):
        print(f"Slice {args.id} marked as in_progress.")
    else:
        print(f"Slice {args.id} not found in SLICES.md.")


def cmd_complete_slice(args: argparse.Namespace) -> None:
    if update_slice_status(args.id, "done"):
        state = read_state()
        state["last_updated"] = TODAY
        write_state(state)
        print(f"Slice {args.id} marked as done.")
    else:
        print(f"Slice {args.id} not found in SLICES.md.")


def cmd_fail_slice(args: argparse.Namespace) -> None:
    if update_slice_status(args.id, "failed"):
        print(f"Slice {args.id} marked as failed.")
    else:
        print(f"Slice {args.id} not found in SLICES.md.")


def cmd_list_slices(_: argparse.Namespace) -> None:
    if not SLICES_PATH.exists():
        print("No SLICES.md found.")
        return
    slices = load_slices()
    if not slices:
        print("No slices found.")
        return

    STATUS_ICONS = {"pending": "[ ]", "in_progress": "[~]", "done": "[x]", "failed": "[!]"}
    id_width = max(len(s["id"]) for s in slices)

    # Group slices by burst, preserving insertion order
    burst_groups: dict[str, list[dict]] = {}
    no_burst: list[dict] = []
    for s in slices:
        burst = s.get("burst", "").strip()
        if burst:
            if burst not in burst_groups:
                burst_groups[burst] = []
            burst_groups[burst].append(s)
        else:
            no_burst.append(s)

    for burst_name, burst_slices in burst_groups.items():
        b_done = sum(1 for s in burst_slices if s["status"] == "done")
        b_total = len(burst_slices)
        print(f"\n{burst_name}  ({b_done}/{b_total})")
        for s in burst_slices:
            icon = STATUS_ICONS.get(s["status"], "[ ]")
            title = s["title"].split(" - ", 1)[-1] if " - " in s["title"] else s["title"]
            print(f"  {icon} {s['id'].ljust(id_width)}  {title}")

    if no_burst:
        print("\n(no burst)")
        for s in no_burst:
            icon = STATUS_ICONS.get(s["status"], "[ ]")
            title = s["title"].split(" - ", 1)[-1] if " - " in s["title"] else s["title"]
            print(f"  {icon} {s['id'].ljust(id_width)}  {title}")

    # Overall progress summary
    total = len(slices)
    done = sum(1 for s in slices if s["status"] == "done")
    failed = sum(1 for s in slices if s["status"] == "failed")
    in_prog = sum(1 for s in slices if s["status"] == "in_progress")
    pct = int(100 * done / total) if total else 0
    summary = f"\nProgress: {done}/{total} done ({pct}%)"
    if in_prog:
        summary += f"  |  {in_prog} in-progress"
    if failed:
        summary += f"  |  {failed} failed"
    print(summary)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Forger CLI -- deterministic markdown-driven workflow helper",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Commands:
  init                    Init project in current directory (creates docs + Kilo Code modes)
  install                 Install Forger modes globally (~/.kilo/custom_modes.yaml)
  status                  Show current workflow state and slice progress
  lock                    Lock project scope (freeze PROJECT.md)
  unlock                  Unlock project scope
  set-interrupt MODE      Set execution interrupt mode (autonomous|per_milestone|per_burst|per_slice)
  reset                   Reset to PLANNING phase (wipe execution artifacts, keep PROJECT.md + contracts)
  plan                    Start planning phase (creates planning doc templates)
  orchestrate             Generate task packets from SLICES.md (validates DAG, detects cycles)
  execute                 Show execution status and how to start the Orchestrator
  next-slice              Print the next pending slice (STALE/QA_PENDING/ALL_DONE aware)
  next-wave               Print all currently unblocked slices for wave-based parallel execution
  start-slice ID          Mark a slice as in_progress
  complete-slice ID       Mark a slice as done
  fail-slice ID           Mark a slice as failed
  list-slices             List all slices grouped by burst with progress counters
""",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("init", help="Init project in current directory").set_defaults(func=cmd_init)
    sub.add_parser("install", help="Install modes globally to ~/.kilo/custom_modes.yaml").set_defaults(func=cmd_install)
    sub.add_parser("status", help="Show current state and slice progress").set_defaults(func=cmd_status)
    sub.add_parser("lock", help="Lock project scope").set_defaults(func=cmd_lock)
    sub.add_parser("unlock", help="Unlock project scope").set_defaults(func=cmd_unlock)

    interrupt_p = sub.add_parser("set-interrupt", help="Set execution interrupt mode")
    interrupt_p.add_argument("mode", choices=["autonomous", "per_milestone", "per_burst", "per_slice"],
                             help="autonomous=no pauses, per_slice/per_burst/per_milestone=pause at boundaries")
    interrupt_p.set_defaults(func=cmd_set_interrupt)

    sub.add_parser("reset", help="Reset to PLANNING phase (wipe execution artifacts)").set_defaults(func=cmd_reset)
    sub.add_parser("plan", help="Start planning phase").set_defaults(func=cmd_plan)
    sub.add_parser("orchestrate", help="Generate task packets (validates DAG, detects cycles)").set_defaults(func=cmd_orchestrate)
    sub.add_parser("execute", help="Show execution status and Orchestrator instructions").set_defaults(func=cmd_execute)
    sub.add_parser("next-slice", help="Get next pending slice").set_defaults(func=cmd_next_slice)
    sub.add_parser("next-wave", help="Get all currently unblocked slices (wave execution)").set_defaults(func=cmd_next_wave)
    sub.add_parser("list-slices", help="List all slices with status").set_defaults(func=cmd_list_slices)

    start_p = sub.add_parser("start-slice", help="Mark slice as in_progress")
    start_p.add_argument("id", help="Slice ID (e.g. S1)")
    start_p.set_defaults(func=cmd_start_slice)

    complete_p = sub.add_parser("complete-slice", help="Mark slice as done")
    complete_p.add_argument("id", help="Slice ID (e.g. S1)")
    complete_p.set_defaults(func=cmd_complete_slice)

    fail_p = sub.add_parser("fail-slice", help="Mark slice as failed")
    fail_p.add_argument("id", help="Slice ID (e.g. S1)")
    fail_p.set_defaults(func=cmd_fail_slice)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
